import type { TalentRankingDataset } from "./types";

export const MOCK_DATASET: TalentRankingDataset = {
  source: "mock",
  fetchedAt: new Date().toISOString(),
  profileTitle: "Alpina Tech — Full-Stack Agency",
  entries: [
    {
      date: "20.01.26",
      weekViews: 312,
      weekInbound: "8%",
      rankings: [
        { keyword: "Next.js", world: 12, europe: 4, ua: 1 },
        { keyword: "Next.js developer", world: 9, europe: 3, ua: 1 },
        { keyword: "React", world: 18, europe: 7, ua: 2 },
        { keyword: "React developer", world: 14, europe: 5, ua: 2 },
        { keyword: "Astro", world: 3, europe: 1, ua: 1 },
        { keyword: "Astro developer", world: 2, europe: 1, ua: 1 },
        { keyword: "Astro CMS", world: 1, europe: 1, ua: 1 },
        { keyword: "Headless", world: 22, europe: 9, ua: 3 },
        { keyword: "Headless developer", world: 17, europe: 6, ua: 2 },
        { keyword: "Headless CMS", world: 11, europe: 4, ua: 1 },
        { keyword: "Strapi", world: 5, europe: 2, ua: 1 },
        { keyword: "Strapi developer", world: 4, europe: 2, ua: 1 },
        { keyword: "Payload", world: 7, europe: 3, ua: 1 },
        { keyword: "Sanity", world: 8, europe: 3, ua: 1 },
      ],
      steps: null,
    },
    {
      date: "27.01.26",
      weekViews: 287,
      weekInbound: "7%",
      rankings: [
        { keyword: "Next.js", world: 10, europe: 3, ua: 1 },
        { keyword: "Next.js developer", world: 8, europe: 3, ua: 1 },
        { keyword: "React", world: 16, europe: 6, ua: 2 },
        { keyword: "React developer", world: 13, europe: 5, ua: 2 },
        { keyword: "Astro", world: 2, europe: 1, ua: 1 },
        { keyword: "Astro developer", world: 2, europe: 1, ua: 1 },
        { keyword: "Astro CMS", world: 1, europe: 1, ua: 1 },
        { keyword: "Headless", world: 20, europe: 8, ua: 3 },
        { keyword: "Headless developer", world: 15, europe: 6, ua: 2 },
        { keyword: "Headless CMS", world: 9, europe: 3, ua: 1 },
        { keyword: "Strapi", world: 4, europe: 2, ua: 1 },
        { keyword: "Strapi developer", world: 3, europe: 2, ua: 1 },
        { keyword: "Payload", world: 6, europe: 3, ua: 1 },
        { keyword: "Sanity", world: 7, europe: 3, ua: 1 },
      ],
      steps:
        "Оновили заголовок профілю: додали 'Astro / Headless CMS specialist'. Перевірили keywords у overview.",
    },
    {
      date: "03.02.26",
      weekViews: 340,
      weekInbound: "11%",
      rankings: [
        { keyword: "Next.js", world: 8, europe: 3, ua: 1 },
        { keyword: "Next.js developer", world: 7, europe: 2, ua: 1 },
        { keyword: "React", world: 15, europe: 5, ua: 1 },
        { keyword: "React developer", world: 11, europe: 4, ua: 1 },
        { keyword: "Astro", world: 2, europe: 1, ua: 1 },
        { keyword: "Astro developer", world: 1, europe: 1, ua: 1 },
        { keyword: "Astro CMS", world: 1, europe: 1, ua: 1 },
        { keyword: "Headless", world: 19, europe: 7, ua: 2 },
        { keyword: "Headless developer", world: 14, europe: 5, ua: 2 },
        { keyword: "Headless CMS", world: 8, europe: 3, ua: 1 },
        { keyword: "Strapi", world: 3, europe: 1, ua: 1 },
        { keyword: "Strapi developer", world: 3, europe: 1, ua: 1 },
        { keyword: "Payload", world: 5, europe: 2, ua: 1 },
        { keyword: "Sanity", world: 6, europe: 2, ua: 1 },
      ],
      steps:
        "Додали кейс-стаді Strapi + Next.js у portfolio. Оновили specializations. Зростання views на 18%.",
    },
    {
      date: "10.02.26",
      weekViews: 398,
      weekInbound: "14%",
      rankings: [
        { keyword: "Next.js", world: 6, europe: 2, ua: 1 },
        { keyword: "Next.js developer", world: 5, europe: 2, ua: 1 },
        { keyword: "React", world: 13, europe: 4, ua: 1 },
        { keyword: "React developer", world: 10, europe: 3, ua: 1 },
        { keyword: "Astro", world: 1, europe: 1, ua: 1 },
        { keyword: "Astro developer", world: 1, europe: 1, ua: 1 },
        { keyword: "Astro CMS", world: 1, europe: 1, ua: 1 },
        { keyword: "Headless", world: 17, europe: 6, ua: 2 },
        { keyword: "Headless developer", world: 12, europe: 4, ua: 1 },
        { keyword: "Headless CMS", world: 6, europe: 2, ua: 1 },
        { keyword: "Strapi", world: 2, europe: 1, ua: 1 },
        { keyword: "Strapi developer", world: 2, europe: 1, ua: 1 },
        { keyword: "Payload", world: 4, europe: 2, ua: 1 },
        { keyword: "Sanity", world: 5, europe: 2, ua: 1 },
      ],
      steps: null,
    },
    {
      date: "17.02.26",
      weekViews: 421,
      weekInbound: "16%",
      rankings: [
        { keyword: "Next.js", world: 5, europe: 2, ua: 1 },
        { keyword: "Next.js developer", world: 4, europe: 1, ua: 1 },
        { keyword: "React", world: 11, europe: 3, ua: 1 },
        { keyword: "React developer", world: 9, europe: 3, ua: 1 },
        { keyword: "Astro", world: 1, europe: 1, ua: 1 },
        { keyword: "Astro developer", world: 1, europe: 1, ua: 1 },
        { keyword: "Astro CMS", world: 1, europe: 1, ua: 1 },
        { keyword: "Headless", world: 15, europe: 5, ua: 2 },
        { keyword: "Headless developer", world: 11, europe: 4, ua: 1 },
        { keyword: "Headless CMS", world: 5, europe: 2, ua: 1 },
        { keyword: "Strapi", world: 2, europe: 1, ua: 1 },
        { keyword: "Strapi developer", world: 2, europe: 1, ua: 1 },
        { keyword: "Payload", world: 3, europe: 1, ua: 1 },
        { keyword: "Sanity", world: 4, europe: 2, ua: 1 },
      ],
      steps:
        "Підняли hourly rate до $65. Відповіли на 3 inbound запити цього тижня. Astro CMS #1 worldwide!",
    },
  ],
};
