import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  type GraphQLSchema,
  type GraphQLField,
  type GraphQLArgument,
  type GraphQLObjectType,
  isObjectType,
} from "graphql";

const CAPABILITIES_PATH = resolve(process.cwd(), "schema", "capabilities.md");

interface Theme {
  id: string;
  title: string;
  blurb: string;
  keywords: RegExp;
}

/**
 * Themes mirror Phase 1 priorities in CLAUDE.md.
 * Order matters: earlier themes claim matching fields first.
 */
const THEMES: Theme[] = [
  {
    id: "messages",
    title: "1. Conversations (messages, rooms, threads)",
    blurb: "Primary Phase 1 focus — client correspondence analysis.",
    keywords: /room|message|thread|chat|inbox|attachment|conversation/i,
  },
  {
    id: "contracts",
    title: "2. Contracts (active + history)",
    blurb: "Agency-scoped contracts; active engagements and historical ledger.",
    keywords: /contract|engagement|workDiary|workdiary|hourly|fixed/i,
  },
  {
    id: "proposals",
    title: "3. Proposals funnel",
    blurb: "Read-only — no auto-apply (banned by Upwork).",
    keywords: /proposal|offer|cover|application/i,
  },
  {
    id: "earnings",
    title: "4. Earnings + payments timeseries",
    blurb: "Transactions, payments, billing; for dashboard charts.",
    keywords: /earning|payment|transaction|invoice|billing|payout|financial/i,
  },
  {
    id: "org",
    title: "5. Organization + identity (foundation)",
    blurb:
      "`user`, `organization`, tenant discovery — needed before anything agency-scoped works.",
    keywords: /^(me|user|organization|company|agency|team|member)/i,
  },
  {
    id: "jobs",
    title: "6. Job / talent search (thin probe only)",
    blurb: "Covering-probe scope. Do not build deep extraction in Phase 1.",
    keywords: /job|talent|posting|marketplace|search|freelancer|skill/i,
  },
];

const OTHER_THEME: Theme = {
  id: "other",
  title: "7. Other",
  blurb:
    "Unclassified queries/mutations — review to decide if they belong in a theme above.",
  keywords: /.*/,
};

function classify(fieldName: string): Theme {
  for (const theme of THEMES) {
    if (theme.keywords.test(fieldName)) return theme;
  }
  return OTHER_THEME;
}

function renderArgs(args: readonly GraphQLArgument[]): string {
  if (args.length === 0) return "";
  const parts = args.map((a) => {
    const req = a.type.toString().endsWith("!") ? "!" : "";
    return `${a.name}: ${a.type.toString()}${req && !a.type.toString().endsWith("!") ? "!" : ""}`;
  });
  return `(${parts.join(", ")})`;
}

function renderField(
  field: GraphQLField<unknown, unknown>,
  kind: "Query" | "Mutation",
): string {
  const check = "- [ ]";
  const sig = `\`${kind}.${field.name}${renderArgs(field.args)}: ${field.type.toString()}\``;
  const desc = field.description?.trim().replace(/\s+/g, " ").slice(0, 200);
  return desc ? `${check} ${sig} — ${desc}` : `${check} ${sig}`;
}

function groupFields(
  root: GraphQLObjectType | null | undefined,
  kind: "Query" | "Mutation",
): Map<string, string[]> {
  const groups = new Map<string, string[]>();
  if (!root) return groups;
  const fields = root.getFields();
  for (const name of Object.keys(fields).sort()) {
    const field = fields[name];
    if (!field) continue;
    const theme = classify(field.name);
    const existing = groups.get(theme.id) ?? [];
    existing.push(renderField(field, kind));
    groups.set(theme.id, existing);
  }
  return groups;
}

export interface CapabilitiesResult {
  path: string;
  totalQueries: number;
  totalMutations: number;
}

export function writeCapabilities(schema: GraphQLSchema): CapabilitiesResult {
  const queryType = schema.getQueryType();
  const mutationType = schema.getMutationType();

  const queryGroups = groupFields(queryType, "Query");
  const mutationGroups = groupFields(mutationType, "Mutation");

  const totalQueries = queryType
    ? Object.keys(queryType.getFields()).length
    : 0;
  const totalMutations = mutationType
    ? Object.keys(mutationType.getFields()).length
    : 0;

  const typeCount = Object.keys(schema.getTypeMap()).filter(
    (n) => !n.startsWith("__"),
  ).length;

  const lines: string[] = [];
  lines.push(`# Upwork GraphQL — capability map`);
  lines.push("");
  lines.push(
    `Generated by \`pnpm cli refresh-schema\`. Treat as a probe backlog: tick the items we want to exercise in Phase 1.`,
  );
  lines.push("");
  lines.push(`- Queries: **${totalQueries}**`);
  lines.push(`- Mutations: **${totalMutations}**`);
  lines.push(`- Types (excluding introspection): **${typeCount}**`);
  lines.push("");
  lines.push(`SDL: [schema/upwork.graphql](./upwork.graphql)`);
  lines.push("");
  lines.push(`---`);
  lines.push("");

  const allThemes = [...THEMES, OTHER_THEME];
  for (const theme of allThemes) {
    const q = queryGroups.get(theme.id) ?? [];
    const m = mutationGroups.get(theme.id) ?? [];
    if (q.length === 0 && m.length === 0) continue;

    lines.push(`## ${theme.title}`);
    lines.push("");
    lines.push(`_${theme.blurb}_`);
    lines.push("");

    if (q.length > 0) {
      lines.push(`### Queries (${q.length})`);
      lines.push("");
      lines.push(...q);
      lines.push("");
    }
    if (m.length > 0) {
      lines.push(`### Mutations (${m.length})`);
      lines.push("");
      lines.push(...m);
      lines.push("");
    }
  }

  const content = lines.join("\n");
  writeFileSync(CAPABILITIES_PATH, content, "utf8");
  return {
    path: CAPABILITIES_PATH,
    totalQueries,
    totalMutations,
  };
}
